
trigger:
- main

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: 'faileann'
  imageRepository: 'ocserver'
  containerRegistry: 'failean.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'failean12fa-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: az acr login --name failean --username $(registryUserName) --password $(registryPassword)
            displayName: 'Login to ACR'
          - task: Docker@2
            inputs:
              command: 'build'
              repository: 'failean.azurecr.io/ocserver'
              dockerfile: '**/Dockerfile'
              buildContext: '$(Build.Repository.LocalPath)'
              arguments: '--build-arg NPMTOKEN=$(npmToken)'
              tags: |
                $(tag)
          - task: Docker@2
            inputs:
              command: 'push'
              repository: 'failean.azurecr.io/mainserver'
              tags: |
                $(tag)
